### ISSUE TITLE
중간고사 발표준비

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#11]

**Comment by bss0727** [comment]
제가 해결방법과 멘토링 관련 부분 발표 맡도록 하겠습니다.

**Comment by wcharibo** [comment]
제가 처음부터 차별성까지 발표하겠습니다. 대본을 여기에 공유하고 닫겠습니다.

**Comment by wcharibo** [comment]
[team500중간발표대본민웅기.docx](https://github.com/wcharibo/sanhak_500/files/9846031/team500.docx)

**Comment by bss0727** [comment]
[team500_Part_2_추가.docx](https://github.com/wcharibo/sanhak_500/files/9846141/team500_Part_2_.docx)
