### ISSUE TITLE
프로젝트 결과 보고서 초안 작성

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#12]
2022-11-05 자정전까지 제출해야합니다.

**Comment by wcharibo** [comment]
제가 특허나 논문 항목은 빼고 나머지는 작성했는데 한글파일이 안올라가지네요

**Comment by wcharibo** [comment]
[10-프로젝트결과보고서.docx](https://github.com/wcharibo/sanhak_500/files/9937436/10-.docx)
변환하니까 이상하게 보이네요
내일 제출 전까지 특허나 논문 찾아보고 내용 수정합시다.

**Comment by wcharibo** [comment]
[10-프로젝트결과보고서.pdf](https://github.com/wcharibo/sanhak_500/files/9937475/10-.pdf)

**Comment by bss0727** [comment]
[Team500-프로젝트결과보고서_1.hwp.pdf](https://github.com/wcharibo/sanhak_500/files/9941559/Team500-._1.hwp.pdf)

제가 너무 늦게 글을 확인했습니다. 올려주신 결과보고서 초안을 바탕으로 나머지 부분을 채워 넣었습니다. 
개발 일정 부분을 표나 그래프로 나타내기만 하면 될 것 같습니다.

영문으로 practice program 이어서 타자 연습 프로그램으로 바꿔 적었습니다.
