### ISSUE TITLE
2차 멘토링 질문 리스트

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#13]
2차 멘토링 때 질문할 내용 적는 곳입니다.

**Comment by bss0727** [comment]
1. 로그인 방식을 구글, 카카오 등의 계정과 연동하여 사용하는 방식에 비한 해당 웹 안에서 회원 가입을 통한 로그인 방식의 장단점
2. 해당 프로젝트에 대한 피드백, 방향성 제시
3. 요구사항정의서에 대한 피드백

1차 멘토링 때 프로젝트 내용에 관한 언급은 하지 않으셨던 것을 토대로 이번 질문 내용을 위와 같이 정해봤습니다.

**Comment by wcharibo** [comment]
1. 현업에서 결과보고서가 가지는 의미
2. 실패한 프로젝트도 결과보고서를 쓰는지?
3. 웹서비스를 제공하는 데에 가장 중요한 점
정도로 작성했습니다. 내일 멘토님 뵙기 전까지 더 생각나는 게 있으면 추가하겠습니다.
