### ISSUE TITLE
2차 멘토링 일지 작성

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#14]
2차 멘토링 일지 작성
제가 사진이 없어서 나머지 내용 작성했고 부족한 부분 있으면 추가해주시고 사진 첨부해서 제출해주세요

**Comment by wcharibo** [comment]
[8-2차프로젝트멘토일지.pdf](https://github.com/wcharibo/sanhak_500/files/9956395/8-2.pdf)
pdf로 첨부했고 한글파일도 카톡으로 보내드릴 수 있습니다.

**Comment by bss0727** [comment]
네 확인 했습니다. 사진 첨부해서 업로드 하겠습니다.
