### ISSUE TITLE
발명설명서, 직무발명신고및권리승계합의서 제출

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#15]
11.26까지 제출해야합니다.

**Comment by bss0727** [comment]
[Team+500+발명설명서.hwp.pdf](https://github.com/wcharibo/sanhak_500/files/10084733/Team%2B500%2B.hwp.pdf)

일단 12주차 발명설명서 PPT를 참고해서 내용을 작성해 보았습니다.
발명의 용도 부분에서 쓸 말이 떠오르지 않아서 주요 고객층을 적어 넣었는데, 사업화 가능성이라던지  특허권을 활용할 수 있는 분야를 어떻게 적어야 할까요?

**Comment by wcharibo** [comment]
저희 프로그램은 기존의 타자 연습 프로그램의 목적은 유지하고 효율성을 높여서 자신의 타자 실력 향상을 원하는 사람들이라면 누구나 해당 프로그램을 통해 목표를 달성할 수 있고, 해당 프로그램이 웹브라우저에서 제공하는 서비스라는 이점을 살려 배너 광고를 통해 수익을 창출할 수 있습니다.
//이 정도가 끝인거 같습니다. 기존의 프로그램들을 봐도 특별하게 하는 게 없어서... 타자연습프로그램이 그 자체로 용도이고 가지고 있는 한계인거 같아요.

**Comment by wcharibo** [comment]
직무발명신고 및 권리승계합의서는 제거 입력해서 카카오톡으로 드리겠습니다.

**Comment by bss0727** [comment]
카카오톡으로 보내주신 파일과 발명의 용도 작성해주신 것 추가해서 교수님께 메일 보내겠습니다.
