### ISSUE TITLE
발명설명서에 관한 ppt 제작

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#16]
12주차에 발명설명서에 관한 ppt 발표 있습니다.

**Comment by bss0727** [comment]
[Team_500_발명설명서 템플릿.pptx](https://github.com/wcharibo/sanhak_500/files/10031517/Team_500_.pptx)
발표에 쓸 ppt 템플릿을 만들었습니다.
구체적인 내용은 추후 상의 후에 기입하여 재업로드 하겠습니다.

**Comment by bss0727** [comment]
[발명설명서_초안.hwp.pdf](https://github.com/wcharibo/sanhak_500/files/10043155/_.hwp.pdf)

**Comment by wcharibo** [comment]
고생하셨습니다. 오늘이나 내일 시간 가능하실 때 ppt를 만들까요?
근데 저희 프로그램 발명으로 하는 거 아니었나요? 시간 측정기를 발명했다고 하기엔 자바스크립트에서 제공하는 거 이용만 하는 거라서...

**Comment by bss0727** [comment]
아 제가 시간 측정기라고 썼네요.
잘못 이해했던것 같습니다.
지금은 시간이 안돼서 8시쯤 가능할까요?

**Comment by wcharibo** [comment]
넵 좋습니다. 선행기술 좀 조사해놔서 보시고 괜찮으면 바로 ppt에 참고할 수 있도록 준비할게요

**Comment by wcharibo** [comment]
[발명.docx](https://github.com/wcharibo/sanhak_500/files/10046774/default.docx)
선행기술 조사를 해본다고 했는 데 관련된 게 몇 개 없네요. 발명을 프로그램으로 바꿔서 작성해봤습니다.

**Comment by bss0727** [comment]
수정해 주신 발명설명서로 ppt를 제작하면 될 것 같습니다.
ppt 초안 제작 후에 공유하겠습니다.

**Comment by wcharibo** [comment]
넵 알겠습니다.

**Comment by bss0727** [comment]
[발명설명서_초안_02.pptx](https://github.com/wcharibo/sanhak_500/files/10046976/_._02.pptx)
집에 친척들이 오셔서 30분정도 시간이 더 걸렸습니다.
 ppt 만들다보니 발명의 용도 부분에 유저 풀을 넣는 것이 약간 의미가 어긋난 듯한 느낌이 드네요
발명 명칭도 조금 다듬었으면 하는데 아이디어 있으신가요?

**Comment by wcharibo** [comment]
맞는 말씀이신 것 같습니다. 유저에 대해 얘기하지말고 앞에서 말했던 내용과 효과로 타이핑 실력 향상을 얘기하고 구독형 서비스나 웹페이지 광고 이외에는 사업화할 부분이 없다는 점을 한계점으로 얘기하는 것은 어떨까요?

발명명칭은 '문자 인지와 입력 사이의 시간을 이용한 타이핑 프로그램' 이렇게 내용도 보여줄 수 있는 형식으로 다듬는 게 좋을 것 같습니다.

**Comment by bss0727** [comment]
[발명설명서_초안_03.pptx](https://github.com/wcharibo/sanhak_500/files/10047078/_._03.pptx)
수정 사항 반영했고 조금 다듬었습니다.
보시고 개선사항 있으면 말씀해주세요.
12주차 발표자료는 업로드 하는 곳이 없는데, 제가 usb가 없어서 혹시 ppt 작업 끝나면 담아가 주실수 있나요?

**Comment by wcharibo** [comment]
예 제가 usb 챙기겠습니다. 
개선사항이 하나 있는 데 발명의 영문 명칭이 A typing program using the time from character recognition to typing으로 바뀌는 게 좋을 것 같습니다. 
아까 제가 드린 word파일 대충 읽어보니까 3분 정도는 나올 것 같은 데 발표는 어떻게 진행할까요?

**Comment by bss0727** [comment]
[발명설명서_개정안_00.pptx](https://github.com/wcharibo/sanhak_500/files/10047130/_._00.pptx)
발표 진행은 지난번처럼 단순하게 앞 뒤 나눠서 하는 거로 하죠.
지난번엔 제가 뒤에 했으니 이번엔 앞에 발표 하겠습니다
분량은 목차부터 3페이지까지 제가 하는게 어떨까요?

**Comment by wcharibo** [comment]
넵 알겠습니다. 대본 작성해서 공유하겠습니다.  점수 채워야 하니까 혹시 발표 준비로 issue 하나 새로 열어주실 수 있을까요?

**Comment by bss0727** [comment]
네 알겠습니다.

**Comment by bss0727** [comment]
[Team 500 발명설명서_발표용.pptx](https://github.com/wcharibo/sanhak_500/files/10049087/Team.500._.pptx)
발표의 배경 페이지에서 발명하게 된 동기 -> 발표의 배경으로 수정했습니다.

**Comment by wcharibo** [comment]
고생하셨습니다. 내일 usb에 발표자료 담아가겠습니다.
