### ISSUE TITLE
12주차 발표 준비 관련 issue

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#18]
12주차 발표 준비 관련 issue

**Comment by bss0727** [comment]
[발명설명서 발표 part_1 대본.docx](https://github.com/wcharibo/sanhak_500/files/10049053/part_1.docx)
1분30초~2분 정도의 시간이 나왔습니다.

**Comment by wcharibo** [comment]
[12주차 발표대본.docx](https://github.com/wcharibo/sanhak_500/files/10049359/12.docx)
저도 1분 30초 정도 입니다.
