### ISSUE TITLE
12주차 Peer-review(유니마켓) comment 목록 

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#19]
12주차 Peer-review(유니마켓) comment 목록

**Comment by bss0727** [comment]
comment
1. DB, 클라우드의 유지, 보수에 대한 예산 문제
2. 클라우드 서비스를 사용함에 따른 보안 문제의 해결 방안을 제시해 주었으면 한다.
3. 데이터를 모을 때 크롤링을 허용하는 범위의 문제가 발생할 것 같다.

**Comment by wcharibo** [comment]
(1) 중고나라 어플들이 너무 많이 생겨나서 구매자가 원하는 물건을 찾기 위해 여러 어플을 통해 찾아봐야 하며 거래 가능한 지역에 원하는 물품이 판매 중인지 확인하는 데에도 수고로움이 존재하여 중고거래 어플들은 통합하는 플랫폼을 만들어 구매자가 원하는 물품을 찾는 수고를 덜고 모니터링을 통해 원하는 물품이 등록되면 알림을 준다. 

(2)problem
	* ’거래 가능한 지역에 사용자가 원하는 상품이 바로 없을 경우가 많고’라고 문제점을 지적하는 부분에서 거래 가능한 지역으로 국한하는 이유가 무엇인지
	* 
(3)solution
	* 등록된 매물을 검색하는 필터링에 대한 설명이 무엇을 필터링할 수 있는 지 알려줬으면 좋겠습니다.
	* 매물을 등록한 판매자의 평가도 제공하는 기능이 있으면 좋겠습니다. (예, 당근의 매너온도, 중고나라에서 표정 이모티콘을 이용한 평가)
	* 중고거래 사이트에는 구매를 원하는 글도 올라오는 데 어떻게 처리하나요
	* 사기 매물의 가격이 저렴하다는 특성을 생각하면 가격 필터링은 사기매물만 보여주는 결과를 도출할 수 있다고 생각합니다.
(4)차별성
	* 상용제품 중 중고다검색은 어떠한 한계점이 있어서 정상적으로 운영되지 않으며 중고거래 앱 통합 서비스는 통합플랫폼으로써 어떠한 차이점이 있어 정상적으로 운영될 것으로 전망하는지 부족합니다.

(5)evaluation
	*  검색 결과만 보여주면 사기피해에 대해 책임 질 일이 없을 것 같은 데 추후에 서비스가 대중화되면 거래어플의 제품에 대한 신뢰 정책을 통일하여 보여준다는 점이 실제로 거래되는 물건이 사기 매물인지 알려주는 지표라면 굳이 책일질 일을 만드는 것 같습니다.  
(6)etc
	*

**Comment by bss0727** [comment]
(1) 중고나라 어플들이 너무 많이 생겨나서 구매자가 원하는 물건을 찾기 위해 여러 어플을 통해 찾아봐야 하며 거래 가능한 지역에 원하는 물품이 판매 중인지 확인하는 데에도 수고로움이 존재하여 중고거래 어플들은 통합하는 플랫폼을 만들어 구매자가 원하는 물품을 찾는 수고를 덜고 모니터링을 통해 원하는 물품이 등록되면 알림을 준다.

(2) problem
* '거래 가능한 지역에 사용자가 원하는 상품이 바로 없을 경우가 많고'라고 문제점을 지적하는 부분에서 거래 가능한 지역으로 국한하는 이유가 무엇인지
* 중고 거래 사이트에서 데이터를 모을 때 크롤링을 허용하는 범위의 문제가 발생할 수 있을 것 같습니다.
* 사기 매물의 가격이 저렴하다는 특성을 생각하면 가격 필터링은 사기매물만 보여주는 결과를 도출할 수 있다고 생각합니다. (solution ⇒ problem)
(3)solution
* 등록된 매물을 검색하는 필터링에 대한 설명이 무엇을 필터링할 수 있는지 알려줬으면 좋겠습니다.
* 매물을 등록한 판매자의 평가도 제공하는 기능이 있으면 좋겠습니다. (예, 당근의 매너온도, 중고나라에서 표정 이모티콘을 이용한 평가)
* 중고거래 사이트에는 구매를 원하는 글도 올라오는 데 어떻게 처리하는지 제시해 주셨으면 합니다.
* 구매자가 어떤 한 물건만을 필요로 하는 것이 아니라면 알림에 범위 기능을 도입해서 그와 비슷한 성능을 가진 물건이 마켓에 등록되었을 때 알림이 오도록 설계해주는 것도 좋을 것 같습니다.
(4)차별성
* 상용제품 중 중고다검색은 어떠한 한계점이 있어서 정상적으로 운영되지 않는 것인지, 또 중고거래 앱 통합 서비스는 통합플랫폼으로써 어떠한 차이점이 있어 정상적으로 운영될 것으로 전망하는지에 대한 정보가 부족합니다.
*카카오, 네이버와 같이 누구나 쉽게 접근할 수 있는 사이트(예: 네이버쇼핑, 쇼핑하우)에서 제공하는 중고 물품 검색 기능과 무엇이 다른지 명시해주세요.
(5)evaluation
* 검색 결과만 보여주면 사기피해에 대해 책임을 질 일이 없을 것 같은데, 추후에 서비스가 대중화되면 거래어플의 제품에 대한 신뢰 정책을 통일하여 보여준다는 점이 실제로 거래되는 물건이 사기 매물인지 알려주는 지표라면 굳이 책일질 일을 만드는 것 같습니다.

**Comment by bss0727** [comment]
(1) 중고나라 어플들이 너무 많이 생겨나서 구매자가 원하는 물건을 찾기 위해 여러 어플을 통해 찾아봐야 하며 거래 가능한 지역에 원하는 물품이 판매 중인지 확인하는 데에도 수고로움이 존재하여 중고거래 어플들은 통합하는 플랫폼을 만들어 구매자가 원하는 물품을 찾는 수고를 덜고 모니터링을 통해 원하는 물품이 등록되면 알림을 준다.

(2) problem
* '거래 가능한 지역에 사용자가 원하는 상품이 바로 없을 경우가 많고'라고 문제점을 지적하는 부분에서 거래 가능한 지역으로 국한하는 이유가 무엇인지
* 중고 거래 사이트에서 데이터를 모을 때 크롤링을 허용하는 범위의 문제가 발생할 수 있을 것 같습니다.
* 사기 매물의 가격이 저렴하다는 특성을 생각하면 가격 필터링은 사기매물만 보여주는 결과를 도출할 수 있다고 생각합니다. (solution ⇒ problem)

(3)solution
* 등록된 매물을 검색하는 필터링에 대한 설명이 무엇을 필터링할 수 있는지 알려줬으면 좋겠습니다.
* 매물을 등록한 판매자의 평가도 제공하는 기능이 있으면 좋겠습니다. (예, 당근의 매너온도, 중고나라에서 표정 이모티콘을 이용한 평가)
* 중고거래 사이트에는 구매를 원하는 글도 올라오는 데 어떻게 처리하는지 제시해 주셨으면 합니다.
* 구매자가 어떤 한 물건만을 필요로 하는 것이 아니라면 알림에 범위 기능을 도입해서 그와 비슷한 성능을 가진 물건이 마켓에 등록되었을 때 알림이 오도록 설계해주는 것도 좋을 것 같습니다.

(4)차별성
* 상용제품 중 중고다검색은 어떠한 한계점이 있어서 정상적으로 운영되지 않는 것인지, 또 중고거래 앱 통합 서비스는 통합플랫폼으로써 어떠한 차이점이 있어 정상적으로 운영될 것으로 전망하는지에 대한 정보가 부족합니다.
*카카오, 네이버와 같이 누구나 쉽게 접근할 수 있는 사이트(예: 네이버쇼핑, 쇼핑하우)에서 제공하는 중고 물품 검색 기능과 무엇이 다른지 명시해주세요.

(5)evaluation
* 검색 결과만 보여주면 사기피해에 대해 책임을 질 일이 없을 것 같은데, 추후에 서비스가 대중화되면 거래어플의 제품에 대한 신뢰 정책을 통일하여 보여준다는 점이 실제로 거래되는 물건이 사기 매물인지 알려주는 지표라면 굳이 책일질 일을 만드는 것 같습니다.

**Comment by bss0727** [comment]
제가 읽어보고 약간 수정해서 다시 올려봤습니다. 그리고 혹시 (5)번 항목 써주신 내용이 이해가 안돼서 설명 부탁드려도 될까요

**Comment by wcharibo** [comment]
지금하고 있는 서비스가 중고매물 검색해주고 사이트로 연결만 시켜주는 거라 만약에 사기를 당했을 때 책임을 지어야 할 여지가 없는 데  추후 발전 방향에서 '거래어플의 제품에 대한 신뢰정책을 통일하여 보여줄 수도 있을 것이다'라고 하는 점이 (제가 잘 이해가 안돼서) 만약 중고나라에 올라온 판매물품에 대해 구매자가 거래하려 할 때 사기가 아니고 안전한 거래가 될 가능성에 대해 보여준다고 하는 것이라면 굳이? 이런 방향으로 발전 시켜야 하느냐 에 대한 코멘트입니다

**Comment by bss0727** [comment]
아 바로 이해했습니다. 감사합니다. 해당 내용 첨부해서 유니마켓 조에 메일 발송하겠습니다
