### ISSUE TITLE
타이핑 데이터 관리용 데이터베이스 생성

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#24]
마이페이지 항목 중 하나인 그래프, 차트 쪽을 구현하면서

타이핑 데이터에 관한 데이터베이스를 만드는 게 낫다고 생각하여 이슈 남깁니다.

**Comment by wcharibo** [comment]
로그인 db에 같이 구현하기에는 무리가 있는 건가요? 제가 잘 몰라서 더 편하신 방향으로 진행하시죠

**Comment by bss0727** [comment]
데이터베이스 관련해서는 제가 알아보겠습니다.
