### ISSUE TITLE
문자입력시간, wpm, 오타율 확인관련 

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#28]
문자입력시간을 문자별로 나타내어 줄 수 있으면 합니다.

**Comment by wcharibo** [comment]
db로 보내기만 하면 돼서 개발시에 저만 확인하고 commit에 추가 못했습니다. 
tps.js 파일 맨 위에 주석과 함께 사용할 변수들을 적어놨었습니다. 
해당 변수를 getResult나 해당 파일 맨 밑 startTimer에 적으시면 확인하실 수 있습니다. 
20개 단어 생성하게 해놔서 getResult는 단어를 다 적어야 결과가 나타나니 html파일에 연습시간 설정하는 부분에서 value를 짧게 설정하시고 console창에서 확인하시는 게 더 편하실 겁니다. 
그리고 alphabetTimeTable에서 나오는 시간은 1/1000초단위입니다.
추가로 해당 이슈에 관련하여 궁금하신 점 있으면 알려주시고 해결됐으면 닫아주세요. :)

**Comment by bss0727** [comment]
타이핑 결과로 나온 errCnt, wpm, alphabetTimeTable 을 DB에 저장하고 이 세가지 데이터에 대한 그래프를 표현할 수 있도록 만들어보겠습니다.
