### ISSUE TITLE
tps.html 관련 질문

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#29]
wpm, errCnt, alphabetTimeTable 이 세가지 변수를 DOM을 써서 값을 받아올 수 있도록 HTML파일과 js 파일을 수정할 수 있을까요?

**Comment by wcharibo** [comment]
html에서 결과창에 오타수, 타자 속도 나오는 것처럼 문자로 표현하라는 말씀이실까요?

**Comment by wcharibo** [comment]
https://martinnoh.tistory.com/entry/javascript%EC%97%90%EC%84%9C-html%EB%A1%9C-%EA%B0%92-%EC%A0%84%EB%8B%AC 찾아보니 이렇게 document.name.value로 전달할수 있고 문자로만 해도 되면 document.name.innerHTML이나 innerText로 가능할 것 같습니다.
