### ISSUE TITLE
로그인 화면 출력 관련

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#31]
사용자가 처음 url로 서비스를 이용하고자 할 때 default로 random mode를 제공하고 recommend mode 이용하려고 버튼을 클릭하면 login을 하도록 하는 방식으로 개발하는 것이 좋을 것 같습니다.

**Comment by bss0727** [comment]
네 알겠습니다. PR 해 주신 것 클론 떠서 돌려봤는데, 타이핑 창이 안뜨더라고요 그래서 제가 홈화면= 랜덤모드로 놓고, 회원가입 -> 로그인-> 타이핑화면(홈화면)으로 설정해놨는데, 필요하시면 공유하겠습니다.

**Comment by bss0727** [comment]
아직 버튼은 따로 안만들었습니다.

**Comment by wcharibo** [comment]
넵 이제 접근되어서 열어봤는데 루트 페이지만 뜨더라구요 어떻게 수정해야하는 지 공유해주세요

**Comment by wcharibo** [comment]
브라우저 창에서 http://127.0.0.1:3000/login으로 하니까 login화면이 나왔는 데 이렇게 접근하는 거 맞을까요?

**Comment by wcharibo** [comment]
로그인 성공하면 타이핑 연습화면 뜨도록 해결했습니다. 근데 저는 타이핑 창이 잘 뜹니다.

**Comment by bss0727** [comment]
저는 npm start 라고 터미널에 입력 후 http://localhost:3000/ 으로 이동하면 타이핑창이 뜹니다. 아직 버튼이랑 연결을 안했기 때문에 주소창 3000/ 뒤에 register을 입력하면 회원가입 창이 띄워집니다.
회원가입을 마치면 로그인창으로 이동되고, 로그인을 마치면 다시 홈화면인 http://localhost:3000/로 이동되어 타이핑 연습을 할 수 있습니다.

**Comment by wcharibo** [comment]
로그인하지 않은 상태에서 추천모드 버튼 누르면 로그인 창 팝업창으로 나타내고 로그인시 localSeesion에 accessToken을 setItem하게 하였습니다
그래서 로그인한 상태에서는 추천모드 버튼 누르면 추천모드 뜰 수 있도록 구현해서 닫도록 하겠습니다.
