### ISSUE TITLE
로그인 DB 접근 권한 허용

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#32]
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT
해당 오류 발생했습니다. 
https://buyandpray.tistory.com/35 이 블로그 보니까 제 IP에 대해서 접근이 허용되지 않은 것 같습니다. 
로그인 DB 접근 권한 허용해주세요.

**Comment by bss0727** [comment]
워크벤치에서 MySQL Connections 옆에 + 버튼 누르고 보내드린 .env 파일의 내용대로 커넥션 해주시면 됩니다.
