### ISSUE TITLE
사용할 언어 제시, 기타 의견 제시

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#4]
C, 파이썬, 자바, 자바스크립트 모두 타자기를 만들 수 있지만 웹에서 사용하기엔 자바스크립트가 제일 무난하고 효율이 좋은 것 같습니다.

타이핑 실수를 하고 난 직후에 다음 문자를 입력하지 않고 바로 수정을 하는 경우는 별로 없으니까 back space로 몇 개의 문자를 지우고 수정하는지도 측정을 할 수 있으면 재미있을 것 같습니다.

**Comment by wcharibo** [comment]
네 저도 자바스크립트가 좋을 것 같아요. 틀리고 추가로 입력한 문자의 개수를 측정하고 어떻게 활용할 수 있을까요?

**Comment by wcharibo** [comment]
맞춤형 타자연습을 제공하려면 아무래도 로그인을 구현하는 게 좋겠죠?

**Comment by bss0727** [comment]
아무래도 타이핑이 나아지는 과정을 눈으로 직접 볼 수 있게 로그인을 구현하는 것이 좋을 것 같고, 
백스페이스를 누른 횟수를 카운팅 하면 될 것 같습니다
