### ISSUE TITLE
마이페이지 버튼 관련

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#41]
제가 우측 상단에 mypage버튼 만들어 뒀습니다. 새로 안만드셔도 됩니다. graph 브랜치 보니까 작업하고 계신거 같아서요. 그냥 tps.ejs에서 nav -> li -> mypage -> a 에 마이페이지 주소 적어주시면 좋을 거 같습니다.

**Comment by bss0727** [comment]
알려주셔서 감사합니다.
작업중이던 버튼명을 Mypage에서 Graph로 변경하도록 하겠습니다.
그래프가 Restart를 눌렀을때 초기화가 안되어서 작업하고있었습니다.
