### ISSUE TITLE
요구사항정의서, 멘토님꼐 할 질문 정해야합니다.

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/sanhak_500#5]
요구사항정의서, 멘토님꼐 할 질문 정해야합니다.
요구사항정의서 초안 만들어오라고 하셨는데 이거 먼저 작성하고 질문 정할까요?

**Comment by bss0727** [comment]
요구사항 초안이 질문 정하는것에 도움이 될 수 있을것 같으니 초안부터 짜놓는게 좋을것 같습니다.
제가 7시쯤 집에 들어갈 것 같은데 그때 해도 괜찮을까요?

**Comment by wcharibo** [comment]
넵 알겠습니다

**Comment by wcharibo** [comment]
대상 시스템 정의
주요 기능 설명
용어 정의

기능적 요구사할

비기능적 요구사항

인터페이스 요구사항

일단은 이렇게 정하면 될 것 같습니다.

**Comment by bss0727** [comment]
조금 더 정리를 해야 할 것 같기는 한데 이렇게 정리 해봤습니다.

목적
- 타이핑 정확도와 속도 개선을 위함.
범위
- 기존 타이핑 연습 프로그램 + 취약 글자의 확인 프로그램

취약 글자 확인 프로그램
1. 타이핑 할 때 어떤 문자를 자주 틀리는지 확인
1-1. 확인 방법 : 타이핑 오류가 발생하면 Back Space를 누름 > Back Space를 가장 마지막에 눌렀을 때의 글자 체크
1-2. 오타가 발생하자마자 다른 글자를 타이핑 하지 않고 바로 수정하지는 않는다고 판단했고, Back Space를 누른 횟수를 카운팅하여 보여줌으로써 오타 발생 후 오타 수정까지 얼마만큼의 시간이 소요되는지 확인 가능 
>> 해당 프로그램 제작의 당위성 부여
2. 로그인을 통해 사용자의 데이터를 축적하여 어떤 문자에서 지속적인 오류가 발생하는지 표 또는 그래프의 형식으로 한눈에 알기 쉽게 표현한다.
2-1. 또한 해당 글자(자주 틀리는 글자)가 많이 포함된 단어 또는 문장을 사용자에게 제공함으로써 타 프로그램보다 오타 수정이 더 잘될 수 있도록 한다.

**Comment by bss0727** [comment]
기능적/비기능적 요구 사항은 어떻게 작성하여야 할까요

**Comment by bss0727** [comment]
기능적 요구사항 (Functional Requirements)
시스템에 주어지는 특정 입력에 대한 시스템이 산출하는 출력을 통해 정의

- 시스템은 어떤 서비스를 제공하는가
- 어떤 입력이 주어졌을 때 어떻게 반응하는가
- 어떤 상황에서 어떻게 행동하는가 
- 시스템이 무엇을 해야 하는지 설명 (기능 or 시스템 서비스)

기능적 사용자 요구사항 : 사용자에 의해 이해될 수 있는 추상적 방법으로 설명
기능적 시스템 요구사항 : 시스템 기능, 입력, 출력, 예외 사항 등 

 ==============================================

비기능적 요구사항 (Non-Functional Requirements)
소프트웨어 기능들에 대한 조건(시스템의 속성)과 제약 사항에 관한 요구사항

- 기능적 요구사항보다 더 결정적인 부분이 될 수 있다 -> why? 이부분이 충족되지 않으면 시스템 이용 가치 X
- 각각의 특징과 서비스보다는 전체적인 시스템에 적용

**Comment by wcharibo** [comment]
- 기능적 요구사항

타이핑 기능

	- 사용자 관리

		 - 회원가입
		 - 로그인
		 - 마이페이지

	- 모드 선택
		- 한글, 영어
		- 자유연습, 추천 단어 연습
		
	- 입력
		- 한 문자씩 입력시간 체크
		- 한 단어 끝난 뒤에 backspace나 space는 측정 안함
		- 문자를 틀린 뒤에 이전 상태로 돌아오기까지 누른 backspace 개수 체크
		- 맞는 문자를 입력한 이후에는 backspace 눌러도 응답없음
		
        - 검사
		- 한 문자씩 검사
		

	- 데이터 출력

		- 한 턴 마다 표시
			- 타자 속도 출력
			- 틀리게 입력한 문자 개수 확인
		- 마이 페이지에서 표시
			- 각 문자별로 입력시간의 평균으로 막대그래프 표시
			- 틀린 뒤에 backspace 누른 개수 확인
			- 날짜별로 타자 속도 출력
			- 날짜별로 틀리게 입력한 문자 개수 확인

데이터 분석 기능

	-데이터 분석
		- 각 문자별로 입력시간의 평균 계산
		- 틀린 뒤에 backspace 누른 개수 계산
	- 입력시간의 평균으로 가장 높은 값의 문자가 포함된 단어 추천


비기능적 요구사항
- 운영 환경
	- 웹
- 성능 
	- ?
- 품질
	- 항상 사용가능
	- 사용자 문의를 위한 개발자 이메일 주소
이렇게 했는데 기능적 요구사항에서 타이핑에 다 집어넣은거 같긴하네요. 
비기능적 요구사항에서는 저희 한글로도 서비스할 거면 문화적 요구도 추가하면 될 것 같습니다.

**Comment by bss0727** [comment]
틀린 문자가 무엇인지 체크할 때 backspace 말고 문자를 틀렸을 때 바로 체크를 할 수 있는 방법이 있을까요?
한컴 타자연습에서는 틀린 글자가 발생하면 빨갛게 표시가 되는데 이 빨간 표시가 발생할 때 바로 카운팅을 한다던가 하는 방식이 더 효율적일거 같아서요

**Comment by wcharibo** [comment]
방법은 찾아봐야 할 것 같은데 다른 웹서비스에서도 말씀주신 방식으로 작동해서 방법만 알면 빨간 표시하고 사이에 카운팅+1 넣으면 될 것 같아요.

**Comment by bss0727** [comment]
그럼 그 방법은 추후에 확실해지면 요구사항 정의서에 추가하기로 하고 위 내용을 양식에 기입하면 될까요?

**Comment by wcharibo** [comment]
그 기능이 타이핑 기능 검사에 있는데 조금 더 구체적으로 적어야 할까요? 교수님이 주신 예시에서는 되게 간략하게 적혀있었어서..

**Comment by bss0727** [comment]
어떤 것이든 교수님께서 하라는 대로 하는 게 제일 좋은거죠.
한 줄로 명확히 이해가 갈 수 있으면 가장 좋을 듯합니다.

**Comment by wcharibo** [comment]
요구사항 ID도 정해야겠네요

**Comment by wcharibo** [comment]
타이핑 기능 -TF
데이터 분석 기능 - DF

운영환경 -OR
성능 - PR
품질 - QR

저희 한글로 서비스는 어떻게 할까요?

**Comment by bss0727** [comment]
한글 서비스는 영문보다 약간 복잡할 듯하긴 한데

**Comment by bss0727** [comment]
영문은 일자형이라서 틀린 문자를 바로 캐치할 수 있는데, 한글은 자음+모음 또는 받침까지 해서 자음 모음 자음 이렇게 한 글자니 어디서 어떻게 틀렸는지 확인하는 것도 조금 더 생각을 해야 할 부분인 듯합니다.

**Comment by wcharibo** [comment]
추후에 고려해보는 걸로 할까요?
아니면 멘토님께 여쭤볼 질문으로 포함시켜도 좋을 것 같아요

**Comment by bss0727** [comment]
네. 멘토님한테 이번에 질문하는 것으로 하는게 좋겠어요

**Comment by bss0727** [comment]
요구사항 ID 는 위에 작성해주신 대로 하고 뒤에 001 002 처럼 숫자를 붙이면 될거같아요

**Comment by wcharibo** [comment]
인터페이스 요구사항

	사용자 인터페이스 요구사항
		웹 기반으로 사용

	내부 시스템 인터페이스 요구사항
		클릭과 키보드 입력을 이용하여 사용
		직관적인 UI

	외부 시스템 인텨페이스 요구사항
		없음

**Comment by bss0727** [comment]
지난번 수업시간 때 말씀해 주셨던 모바일 앱으로 이 프로그램을 사용하는 것을 생각해 봤었는데, 이 프로그램이 개개인마다 좀 많은 데이터를 필요로 하는데 이 타이핑 교정 프로그램을 모바일로 사용하는 사람이 있을까 하는 회의적인 생각이 들더라구요.

**Comment by wcharibo** [comment]
아 그때 말씀드린 거는 어차피 저희가 웹으로 제공하니까 휴대폰에서도 그냥 사파리나 크롬같이 웹으로 접근하면 UI 크기만 화면에 맞게 줄여주면  알아서 작동할 것 같다고 한거였어요. 따로 만들 필요 없이

**Comment by bss0727** [comment]
아아 모바일로 해당 프로그램을 사용한다 측면이 아니라 모바일로도 작동이 된다는 것을 보여줄 수 있을 거라는 내용이었네요. 이해했습니다.

**Comment by bss0727** [comment]
타이핑 기능 -TF
데이터 분석 기능 - DF
운영환경 -OR
성능 - PR
품질 - QR
위 요구사항별 세부 설정들을 정해야 할 듯합니다.

**Comment by bss0727** [comment]
샘플에 있는 기능 중에서 WF에 사용자 관리 기능, 프로그램 이용 기능을 추가하는 것도 좋을 것 같습니다. 로그인을 통해서 주로 틀리는 부분을 알아간다는 것이니까요.

**Comment by wcharibo** [comment]
TF안에 입력해놨는데 어떤거 말씀하시는 건가요?

**Comment by bss0727** [comment]
아 TF 안의 사용자 관리 탭이 잘려서 안보였던 것 같습니다. 죄송합니다.

**Comment by wcharibo** [comment]
기능적 요구사항

TF 타이핑 기능

	TF1 사용자 관리

		TF1.1. 회원가입
			TF 1.1.1. 사용자는 회원가입 시 정보( 아이디, 비밀번호)를 입력해야 한다. 
			TF 1.1.2. 사용자는 기존 사용자와 중복되는 아이디를 사용할 수 없다. 
		TF1.2. 로그인
			TF1.2.1. 사용자는 회원가입 시 등록한 아이디와 비밀번호로 로그인할 수 있다.
		TF1.3. 마이페이지
			TF1.3.1. 사용자는 날짜별로 타자 속도를 볼 수 있다. 
			TF1.3.1. 사용자는 날짜별로 틀린 타자의 개수를 볼 수 있다. 
			TF1.3.1. 사용자는 날짜별로 틀린 뒤에 backspace를 누른 개수를 확인할 수 있다.
			TF1.3.1. 사용자는 각 문자별로 입력시간의 평균을 표시한 그래프를 볼 수 있다. 
			TF1.3.1. 사용자는 타자 연습 페이지로 이동할 수 있다. 

	TF2 모드 선택

		TF2.1. 연습모드 선택
			TF2.1.1. 사용자는 자유연습, 추천 단어 연습 모드를 선택할 수 있다. 

	TF3 입력

		TF3.1. 입력시간 체크
			TF3.1.1사용자가 입력한 한 문자씩 입력시간 체크
		TF3.2. backspace 체크			
			TF3.2.1. 문자를 틀린 뒤에 이전 상태로 돌아오기까지 누른 backspace 개수 체크한다.
			TF3.2.2. 틀린 문자 수정이 없는 backspace입력은 측정에 포함되지 않는다.

        TF4 검사

		TF4.1. 한 문자 단위로 검사하여 맞게 입력하면 파란색 틀리게 입력하면 빨간색으로 표시한다. 
			

	TF5 데이터 출력

		TF5.1. 한 턴 마다 표시
			TF5.1.1. 사용자가 타자연습 한 턴을 끝내면 타자 속도를 출력한다.
			TF5.1.2. 사용자가 타자연습 한 턴을 끝내면 틀리게 입력한 문자 개수를 출력한다.
		TF5.2. 마이 페이지에서 표시
			TF5.2.1. 각 문자별로 입력시간의 평균으로 막대그래프 표시한다.
			TF5.2.2. 틀린 뒤에 backspace 누른 개수 표시한다.
			TF5.2.3. 날짜별로 타자 속도 선 그래프로 표시한다.
			TF5.2.4. 날짜별로 틀리게 입력한 문자 개수 선 그래프로 표시한다.

DF 데이터 분석 기능

	DF1데이터 분석

		DF1.1. 각 문자별로 입력시간의 평균 계산한다.
		DF1.2. 틀린 뒤에 backspace 누른 개수 계산한다.

	DF2 단어 추천

		DF2.1. 입력시간의 평균으로 가장 높은 값의 문자가 포함된 단어들을 추천 연습 모드로 제공한다.




비기능적 요구사항

OR 조직요구사항

	OR1. 배포
		OR1.1. 사용자는 웹 브라우저를 이용해서 서비스를 이용할 수 있다.
	OR2. 구현
		OR2.1. javascript, css, html을 이용해서 웹서비스를 구현한다.

QR 품질

	QR1. 항상 사용가능
	QR2. as
		QR2.1. 개발자의 이메일 주소로 사용자는 문의를 할 수 있다. 

인터페이스 요구사항

	UIF 사용자 인터페이스 요구사항

		UIF1. 웹 브라우저로 사용할 수 있다.

	IIF 내부 시스템 인터페이스 요구사항

		IIF1. 클릭과 키보드 입력을 이용하여 사용 모든 기능을 사용할 수 있다.
		IIF2. 직관적인 UI로 사용자가 서비스를 이용하는데 불편함이 없어야 한다.

	EIF 외부 시스템 인텨페이스 요구사항

		없음

**Comment by bss0727** [comment]
TF3.2.3. 맞는 문자를 입력한 이후에는 backspace 눌러도 응답없음
여기에서 '응답'이 backspace를 무시한다는 것인지, 틀린 문자 체크에 포함이 되지 않는 것인지 명시 되었으면 좋겠습니다.

**Comment by wcharibo** [comment]
둘 다 포함하는 의미로 쓴거라 어떻게 수정해야 할까요?

**Comment by bss0727** [comment]
backspace 키입력이 되지 않는다는 것인가요?

**Comment by bss0727** [comment]
틀린문자 수정이 없는 backspace 입력은 측정에 포함되지 않는다 라고 한다면 어떨까요?

**Comment by wcharibo** [comment]
오 좋네요

**Comment by bss0727** [comment]
위에서 얘기했던 멘토님께 할 질문을 조금 정리해 봤습니다.
- 영문자는 받침이 없고 단어가 일자형이기 때문에 오타가 발생한 부분을 측정해서 그래프나 표의 형태로 나타내기 쉽습니다. 하지만 한글의 경우에는 틀린 문자를 수정할 때 자음과 모음을 한꺼번에 지우는 형식이라 틀린 부분을 명확히 짚어내기가 어렵다. 이 부분을 어떻게 해결하여야 할까요?

**Comment by wcharibo** [comment]
위에 요구사항 정의 정리해놨습니다. 혹시 문서화 해주실 수 있을까요? 멘토님께 질문은 issue하나 더 열어서 내일까지 자유롭게 
의견 추가하는 거 어떠실까요?

**Comment by bss0727** [comment]
제가 샘플 요구사항 정의서 양식에 맞게 문서화 해서 공유하겠습니다.
여기서 질문사항까지 전부 하는 것보다 내일까지 시간을 들이는게 더 좋을 것 같네요.

혹시 질문거리가 이번 프로젝트 내용에 국한된 것이어야만 하나요?

**Comment by wcharibo** [comment]
교수님이 따로 질문 주제를 국한시키시진 않으셨던거 같아요

**Comment by bss0727** [comment]
네 알겠습니다.
오늘 수고하셨어요.

**Comment by wcharibo** [comment]
넵 고생하셨습니다.

**Comment by wcharibo** [comment]
[Team_500_요구사항정의서+초안.pdf](https://github.com/wcharibo/sanhak_500/files/9640708/Team_500_.%2B.pdf)
초안생성으로 종료합니다.
