### ISSUE TITLE
4주차 질문사항

### ISSUE THREAD

**Issue by bss0727** [wcharibo/sanhak_500#6]
1. 영문자는 받침이 없고 단어가 일자형이기 때문에 오타가 발생한 부분을 측정해서 그래프나 표의 형태로 나타내기 쉽습니다. 하지만 한글의 경우에는 틀린 문자를 수정할 때 자음과 모음을 한꺼번에 지우는 형식이라 틀린 부분을 명확히 짚어내기가 어려울 것 같은데, 이 부분을 어떻게 해결하여야 할까요?
2. 사용 가능한 기술에 대한 란을 자기소개서에서 자주 보았는데, 여기서 사용 가능한 기술이란 어느 정도의 수준을 갖춘 언어나 기술을 말하는 것인가요?
3. 면접을 볼 때 어느 부분을 가장 중요시 보나요??

**Comment by wcharibo** [comment]
4. 서비스를 완성시키고 아무도 써주지 않으면 쓸모가 없을텐데 어떻게 많은 사람들이 쓰게할 수 있을까요? 저의 경우는 유튜브에서 키보드 관련 영상을 시청하다가 타이핑 웹서비스가 있다는 것을 알게되었습니다. 다른 방법이 있을까요?

5. 추천 연습모드에서 추천해주는 단어를 분류할 때 개발자가 일일이 특정 문자를 포함한 단어들로 그룹을 만들어 줄 수도 있겠지만 다른 방법이 있을까요?

**Comment by bss0727** [comment]
프로젝트 관련 질문 3개 비관련 질문 2개 해서 총 질문 다섯개 취합해서 정리할까요

**Comment by wcharibo** [comment]
내일 저희 멘토님 대면으로 뵈니까 굳이 정리 안하고 여기에 대답해주시는 거 바로 적어놔도 괜찮을 거 같아요. 멘토님 의견 적으면서 이슈 close해요

**Comment by bss0727** [comment]
네 알겠습니다.

**Comment by wcharibo** [comment]
잘못 눌러서 닫았었네요
